Repository project-redbud/FunGame-Core, pull requests merged in 2023-12, with the labels that each got.

#65 完善Room的构造函数和SQLScript
  Api/Factory/RoomFactory.cs
  Api/Utility/Factory.cs
  Docs/api.xml
  Entity/System/Room.cs
  Library/Common/JsonConverter/RoomConverter.cs
  Library/SQLScript/Entity/RoomQuery.cs
Labels: continue

#68 完善插件模组系统
  Api/Utility/GameModeLoader.cs
  Api/Utility/PluginLoader.cs
  Controller/AddonController.cs
  Controller/RunTimeController.cs
  Docs/FunGame.Core.xml
  Interface/Base/IAddon.cs
  Interface/Base/IAddonController.cs
  Interface/Base/IGameMode.cs
  Interface/Base/IGameModeServer.cs
  Interface/Base/IPlugin.cs
  Interface/Base/IServerModel.cs
  Interface/Event/GamingEvents.cs
  Library/Common/Addon/GameMode.cs
  Library/Common/Addon/GameModeServer.cs
  Library/Common/Addon/Plugin.cs
  Library/Constant/TypeEnum.cs
  Service/AddonManager.cs
Labels: feature, continue

#69 添加输出Error日志的方法
  Controller/AddonController.cs
  Docs/FunGame.Core.xml
Labels: enhancement

#71 添加写错误日志的工具方法；修改根据格式获取日期字符串的方法
  Api/Utility/General.cs
  Api/Utility/TextReader.cs
  Docs/FunGame.Core.xml
  Library/Common/Network/ServerSocket.cs
  Library/Common/Network/Socket.cs
  Library/Constant/TypeEnum.cs
  Service/JsonManager.cs
  Service/MailManager.cs
Labels: feature, continue
