Repository project-redbud/FunGame-Core, pull requests merged in 2024-08, with the labels that each got.

#81 统一命名 并禁止GameModuleServer调用DataRequest
  Api/Factory/RoomFactory.cs
  Api/Transmittal/DataRequest.cs
  Api/Utility/Factory.cs
  Api/Utility/GameModuleLoader.cs
  Api/Utility/Implement.cs
  Api/Utility/PluginLoader.cs
  Controller/AddonController.cs
  Controller/BaseAddonController.cs
  Docs/FunGame.Core.xml
  Entity/System/Room.cs
  Interface/Base/Addons/IAddonController.cs
  Interface/Base/Addons/IGameMode.cs
  Interface/Base/Addons/IGameModule.cs
  Interface/Base/Addons/IGameModuleDepend.cs
  Interface/Base/Addons/IGameModuleServer.cs
  Interface/Base/Addons/IPlugin.cs
  Interface/Base/IServerModel.cs
  Interface/Event/GamingEventHandlers.cs
  Interface/Event/GamingEvents.cs
  Interface/General/IServer.cs
  Library/Common/Addon/CharacterModule.cs
  Library/Common/Addon/Example/ExampleGameModule.cs
  Library/Common/Addon/Example/ExamplePlugin.cs
  Library/Common/Addon/GameModule.cs
  Library/Common/Addon/GameModuleDepend.cs
  Library/Common/Addon/GameModuleServer.cs
  Library/Common/Addon/ItemModule.cs
  Library/Common/Addon/Plugin.cs
  Library/Common/Addon/SkillModule.cs
  Library/Common/Event/GamingEventArgs.cs
  Library/Common/Event/RoomEventArgs.cs
  Library/Common/JsonConverter/RoomConverter.cs
  Library/Constant/ConstantSet.cs
  Library/Constant/FunGameInfo.cs
  Library/Constant/MethodEnum.cs
  Library/Constant/TypeEnum.cs
  Library/Exception/Exception.cs
  Library/SQLScript/Entity/RoomQuery.cs
  Model/Gaming.cs
  Service/AddonManager.cs
Labels: feature, continue

#82 DataRequest、GameModule相关优化
  Api/Factory/ItemFactory.cs
  Api/Factory/SkillFactory.cs
  Api/Transmittal/DataRequest.cs
  Api/Transmittal/WebDataRequest.cs
  Api/Utility/Factory.cs
  Api/Utility/GameModuleLoader.cs
  Api/Utility/General.cs
  Controller/AddonController.cs
  Controller/RunTimeController.cs
  Controller/SocketHandlerController.cs
  Docs/FunGame.Core.xml
  Entity/BaseEntity.cs
  Entity/Character/Character.cs
  Entity/Item/ActiveItem.cs
  Entity/Item/Item.cs
  Entity/Item/PassiveItem.cs
  Entity/Skill/ActiveSkill.cs
  Entity/Skill/PassiveSkill.cs
  Entity/Skill/Skill.cs
  Interface/Base/Addons/IGameModuleServer.cs
  Interface/Base/HTTP/IHTTPClient.cs
  Interface/Base/IServerModel.cs
  Interface/Base/Sockets/IClientSocket.cs
  Interface/Entity/Base/ICopyable.cs
  Interface/Event/GamingEventHandlers.cs
  Interface/Event/GamingEvents.cs
  Library/Common/Addon/Example/ExampleGameModule.cs
  Library/Common/Addon/GameModule.cs
  Library/Common/Addon/GameModuleDepend.cs
  Library/Common/Addon/GameModuleServer.cs
  Library/Common/Network/ClientSocket.cs
  Library/Common/Network/HTTPClient.cs
  Library/Common/Network/Socket.cs
  Library/Exception/Exception.cs
  Model/Gaming.cs
  Service/AddonManager.cs
Labels: enhancement, feature

#83 加载器、服务器模组、地图优化
  Api/Utility/GameModuleLoader.cs
  Docs/FunGame.Core.xml
  Library/Common/Addon/Example/ExampleGameModule.cs
  Library/Common/Addon/Example/ExamplePlugin.cs
  Library/Common/Addon/GameMap.cs
  Library/Common/Addon/GameModule.cs
  Library/Common/Addon/GameModuleServer.cs
  Library/Common/Addon/Grid.cs
  Service/AddonManager.cs
Labels: enhancement

#84 #80：为Addon添加了专用的DataRequest方法
  Api/Transmittal/DataRequest.cs
  Controller/RunTimeController.cs
  Docs/FunGame.Core.xml
  Library/Common/Network/ServerSocket.cs
  Library/Constant/ConstantSet.cs
  Library/Constant/TypeEnum.cs
  Model/RoomList.cs
  Service/ModelManager.cs
Labels: enhancement
