Repository project-redbud/FunGame-Core, pull requests merged in 2025-01, with the labels that each got.

#104 完善 WebSocket 支持；防止 SQL 注入；修改 Json 自定义转换器基类
  Api/Transmittal/SQLHelper.cs
  Api/Utility/TaskScheduler.cs
  Controller/RunTimeController.cs
  Entity/Character/CharacterBuilder.cs
  Entity/System/Inventory.cs
  Interface/Base/IEntityConverter.cs
  Library/Common/Architecture/Authenticator.cs
  Library/Common/Architecture/BaseEntityConverter.cs
  Library/Common/JsonConverter/CharacterConverter.cs
  Library/Common/JsonConverter/ClubConverter.cs
  Library/Common/JsonConverter/EffectConverter.cs
  Library/Common/JsonConverter/EquipSlotConverter.cs
  Library/Common/JsonConverter/InventoryConverter.cs
  Library/Common/JsonConverter/ItemConverter.cs
  Library/Common/JsonConverter/MagicResistanceConverter.cs
  Library/Common/JsonConverter/NormalAttackConverter.cs
  Library/Common/JsonConverter/RoomConverter.cs
  Library/Common/JsonConverter/SkillConverter.cs
  Library/Common/JsonConverter/UserConverter.cs
  Library/Common/Network/HTTPClient.cs
  Library/SQLScript/Common/Common.cs
  Library/SQLScript/Common/VerifyCodes.cs
  Library/SQLScript/Entity/RoomQuery.cs
  Library/SQLScript/Entity/UserQuery.cs
Labels: enhancement, feature

#107 加载项控制器修改
  Api/Utility/JsonTool.cs
  Controller/BaseAddonController.cs
  Controller/ServerAddonController.cs
Labels: enhancement

#108 fix: 读取 Level 应该先读取 SkillType
  Library/Common/JsonConverter/SkillConverter.cs
Labels: bug
