Repository project-redbud/FunGame-Core, pull requests merged in 2025-04, with the labels that each got.

#118 补全数据库表、查询常量类
  Api/Utility/Factory.cs
  Api/Utility/StringExtension.cs
  Entity/Item/Item.cs
  Entity/System/Inventory.cs
  Entity/System/MarketItem.cs
  Entity/System/Offer.cs
  FunGame.Core.csproj
  Library/Common/JsonConverter/UserConverter.cs
  Library/Constant/ConstantSet.cs
  Library/Constant/FunGameInfo.cs
  Library/Constant/StateEnum.cs
  Library/Constant/TypeEnum.cs
  Library/SQLScript/Common/ApiTokens.cs
  Library/SQLScript/Common/Common.cs
  Library/SQLScript/Common/Configs.cs
  Library/SQLScript/Common/ServerLoginLogs.cs
  Library/SQLScript/Common/UserLogs.cs
  Library/SQLScript/Common/UserSignIns.cs
  Library/SQLScript/Constant.cs
  Library/SQLScript/Entity/GoodsItemsQuery.cs
  Library/SQLScript/Entity/GoodsPricesQuery.cs
  Library/SQLScript/Entity/GoodsQuery.cs
  Library/SQLScript/Entity/InventoriesQuery.cs
  Library/SQLScript/Entity/MarketItemsQuery.cs
  Library/SQLScript/Entity/OfferItemsQuery.cs
  Library/SQLScript/Entity/OffersQuery.cs
  Library/SQLScript/Entity/RoomQuery.cs
  Library/SQLScript/Entity/StoreGoodsQuery.cs
  Library/SQLScript/Entity/StoreQuery.cs
  Library/SQLScript/Entity/UserCharactersQuery.cs
  Library/SQLScript/Entity/UserItemsQuery.cs
  Library/SQLScript/Entity/UserQuery.cs
  Library/SQLScript/fungame.sql
  Library/SQLScript/fungame_sqlite.sql
  NOTICE
Labels: feature

#125 平衡常数类下放至实体/模型级别管理；行动顺序表模型大幅优化（区别自动化）
  Entity/BaseEntity.cs
  Entity/Character/Character.cs
  Entity/Character/Unit.cs
  Entity/Item/Item.cs
  Entity/Skill/NormalAttack.cs
  Entity/Skill/Skill.cs
  Entity/System/Inventory.cs
  Entity/System/Quest.cs
  Entity/System/Store.cs
  Interface/Base/IGamingQueue.cs
  Library/Constant/ConstantSet.cs
  Library/Constant/TypeEnum.cs
  Model/ActionQueue.cs
  Model/EquilibriumConstant.cs
Labels: enhancement, feature

#127 新增用户资料
  Api/Utility/Factory.cs
  Entity/User/UserProfile.cs
  Library/Common/JsonConverter/RoomConverter.cs
  Library/Constant/ConstantSet.cs
  Library/Constant/TypeEnum.cs
  Library/SQLScript/Entity/RoomQuery.cs
  Library/SQLScript/Entity/UserProfilesQuery.cs
  Library/SQLScript/fungame.sql
  Library/SQLScript/fungame_sqlite.sql
  Model/Gaming.cs
Labels: enhancement

#129 添加免疫、驱散；顺序表、爆发技、助攻修改
  Controller/RunTimeController.cs
  Entity/Character/AssistDetail.cs
  Entity/Character/Character.cs
  Entity/Character/MagicResistance.cs
  Entity/Character/Shield.cs
  Entity/Item/Item.cs
  Entity/Skill/Effect.cs
  Entity/Skill/NormalAttack.cs
  Entity/Skill/OpenSkill.cs
  Entity/Skill/Skill.cs
  Entity/Statistics/CharacterStatistics.cs
  Entity/System/Inventory.cs
  Entity/System/RoundRecord.cs
  Interface/Base/IGamingQueue.cs
  Library/Common/JsonConverter/CharacterConverter.cs
  Library/Common/JsonConverter/NormalAttackConverter.cs
  Library/Common/JsonConverter/ShieldConverter.cs
  Library/Constant/ConstantSet.cs
  Library/Constant/StateEnum.cs
  Library/Constant/TypeEnum.cs
  Model/ActionQueue.cs
  Service/JsonManager.cs
Labels: enhancement, feature

#131 fix: 重复队列和负数时间流逝
  Model/ActionQueue.cs
Labels: bug
